// list.vue columns,
export default [
  {
    title: "订单号",
    width: 160,
    align: "center",
    key: "orderNo",
  },
  {
    title: "微信单号",
    width: 134,
    align: "center",
    key: "tradeNo",
  },
  {
    title: "优惠券ID",
    width: 100,
    align: "center",
    key: "couponId",
  },
  {
    title: "优惠券名称",
    width: 190,
    align: "center",
    key: "couponName",
  },
  {
    title: "数量",
    width: 100,
    align: "right",
    key: "couponCount",
  },
  {
    title: "品牌名称",
    width: 190,
    align: "center",
    key: "brandName",
  },
  {
    title: "商户名称",
    width: 190,
    align: "center",
    key: "merchantName",
    slot: "merchantName",
  },
  {
    title: "交易金额（元）",
    width: 150,
    align: "right",
    key: "orderAmount",
  },
  {
    title: "支付通消费（元）",
    width: 150,
    align: "right",
    key: "payChannelFee",
  },
  {
    title: "平台分账含通消费（元）",
    width: 190,
    align: "right",
    key: "totalFee",
  },
  {
    title: "商户分账（元）",
    width: 150,
    align: "right",
    key: "paidAmount",
  },
  {
    title: "支付方式",
    width: 100,
    align: "center",
    key: "payTypeDesc",
  },
  {
    title: "交易类型",
    width: 100,
    align: "center",
    key: "tradeTypeDesc",
  },
  {
    title: "交易时间",
    width: 150,
    align: "center",
    key: "tradeTime",
  },
];

// 商户 mechants columns
export const mechantsColumns = [
  {
    title: "订单号",
    width: 160,
    align: "center",
    key: "orderNo",
  },
  {
    title: "微信单号",
    width: 134,
    align: "center",
    key: "tradeNo",
  },
  {
    title: "优惠券ID",
    width: 100,
    align: "center",
    key: "couponId",
  },
  {
    title: "优惠券名称",
    width: 190,
    align: "center",
    key: "couponName",
  },
  {
    title: "数量",
    width: 100,
    align: "right",
    key: "couponCount",
  },
  {
    title: "品牌名称",
    width: 190,
    align: "center",
    key: "brandName",
  },
  {
    title: "商户名称",
    width: 190,
    align: "center",
    key: "merchantName",
    slot: "merchantName",
  },
  {
    title: "交易金额（元）",
    width: 150,
    align: "right",
    key: "orderAmount",
  },
  {
    title: "支付通消费（元）",
    width: 150,
    align: "right",
    key: "payChannelFee",
  },
  {
    title: "平台分账含通消费（元）",
    width: 190,
    align: "right",
    key: "totalFee",
  },
  {
    title: "商户分账（元）",
    width: 150,
    align: "right",
    key: "paidAmount",
  },
  {
    title: "支付方式",
    width: 100,
    align: "center",
    key: "payTypeDesc",
  },
  {
    title: "交易类型",
    width: 100,
    align: "center",
    key: "tradeTypeDesc",
  },
  {
    title: "交易时间",
    width: 150,
    align: "center",
    key: "tradeTime",
  },
];

// 商超 business columns
export const businessColumns = [
  {
    title: "订单号",
    width: 160,
    align: "center",
    key: "orderNo",
  },
  {
    title: "微信单号",
    width: 134,
    align: "center",
    key: "tradeNo",
  },
  {
    title: "优惠券ID",
    width: 100,
    align: "center",
    key: "couponId",
  },
  {
    title: "优惠券名称",
    width: 190,
    align: "center",
    key: "couponName",
  },
  {
    title: "数量",
    width: 100,
    align: "right",
    key: "couponCount",
  },
  // {
  //   title: '品牌名称',
  //   width: 190,
  //   align: 'center',
  //   key: 'brandName',
  // },
  {
    title: "零售商名称",
    width: 190,
    align: "center",
    key: "brandIdStr",
    slot: "brandIdStr",
  },
  {
    title: "交易金额（元）",
    width: 150,
    align: "right",
    key: "orderAmount",
  },
  {
    title: "支付通消费（元）",
    width: 150,
    align: "right",
    key: "payChannelFee",
  },
  {
    title: "平台分账含通消费（元）",
    width: 190,
    align: "right",
    key: "totalFee",
  },
  {
    title: "商户分账（元）",
    width: 150,
    align: "right",
    key: "paidAmount",
  },
  {
    title: "支付方式",
    width: 100,
    align: "center",
    key: "payTypeDesc",
  },
  {
    title: "交易类型",
    width: 100,
    align: "center",
    key: "tradeTypeDesc",
  },
  {
    title: "交易时间",
    width: 150,
    align: "center",
    key: "tradeTime",
  },
];
